spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        generate_statistics: false
        
  h2:
    console:
      enabled: true
      path: /h2-console
      
  flyway:
    enabled: false  # Désactivé en test car on utilise ddl-auto=create-drop
    
  data:
    redis:
      host: localhost
      port: 6379
      database: 1  # Base différente pour les tests
      timeout: 1000ms

# Configuration JWT pour tests (tokens plus courts)
jwt:
  secret: testSecretKeyForUnitTestsOnly
  expiration: 600000  # 10 minutes seulement pour les tests
  
cors:
  allowed-origins: "*"

# Configuration de test
app:
  upload:
    base-dir: ${java.io.tmpdir}/test-uploads
    temp-dir: ${java.io.tmpdir}/test-temp
    
  security:
    password:
      min-length: 6  # Plus court pour faciliter les tests

# Logs minimaux en test
logging:
  level:
    root: WARN
    com.logement.etudiants: INFO
    org.springframework.test: INFO
    org.testcontainers: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Configuration Actuator pour tests
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# Configuration spécifique aux tests
debug: false