spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/annoncesdb
    username: ${DB_USERNAME:Hydra}
    password: ${DB_PASSWORD:123@Emma}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: HikariCP-Dev
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        generate_statistics: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  h2:
    console:
      enabled: false

# Configuration développement
jwt:
  expiration: 86400000   # 24 heures pour dev
  
cors:
  allowed-origins:
    - 'http://localhost:4200'
    - 'http://localhost:3000'
    - 'http://127.0.0.1:4200'
    - 'swagger-ui/**'
    - '/v3/api-docs*/**'
    - '/**'

# Logs détaillés en développement
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.logement.etudiants: DEBUG
  pattern:
    console: "%clr(%d{ISO8601}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# Configuration Actuator pour développement
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always

# Configuration de développement pour upload
app:
  upload:
    base-dir: ${user.home}/uploads/annonces-dev
    temp-dir: ${java.io.tmpdir}/annonces-temp

# Configuration spécifique dev
debug: false