spring:
  profiles:
    include: secret
  application:
    name: annonces-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/logement_etudiants
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  expiration: 86400000

cors:
  allowed-origins: http://localhost:4200,http://localhost:3000